// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkncnvpvpcvhkbcspmok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbmNudnB2cGN2aGtiY3NwbW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzUwOTYsImV4cCI6MjA2NjE1MTA5Nn0.fkwvAgNBIH2g7Yf_0u6H_ly_3pQDL5suBtWcwJmqcDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);